spring:
  application:
    name: resourceManagement
    
  datasource:
    url: jdbc:mysql://localhost:3306/resource_management_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password_mysql_kamu # <-- Ganti dengan password MySQL Anda
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect